# apiVersion: v1
# kind: Service
# metadata:
#   name: gpt-hf-service
# spec:
#   type: NodePort
#   selector:
#     app: gpt-hf-pod
#   ports:
#   - port: 8000 
#     targetPort: 8000
#     nodePort: 30007
apiVersion: v1
kind: Service
metadata:
  name: gpt-hf-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: gpt-hf-pod
  ports:
    - name: http
      port: 8000
      targetPort: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gpt-hf-ingress
  namespace: default
  annotations:
    # optional: keep client IP in logs, etc.
    nginx.ingress.kubernetes.io/proxy-body-size: "32m"
spec:
  ingressClassName: nginx
  rules:
    - host: gpt.127.0.0.1.sslip.io   
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gpt-hf-service
                port:
                  number: 8000
